features:
  prevent-enderpearl-chunkloading: true
  prevent-moving-into-unloaded-chunks: true
  autosave-interval-seconds: 600
  lobotomize-villagers:
    enabled: true

breeding-cap:
  enabled: true

mob-spawning:
  zombie-reinforcements:
    enforce-mobcap: true
    additional-capacity: 55

  monster-spawners:
    enforce-mobcap: true
    additional-capacity: 55

  infested:
    enforce-mobcap: true
    additional-capacity: 55

  categories:
    - category: 'MONSTER'
      mobcap: 15
      spawn-interval: 1

    - category: 'CREATURE'
      mobcap: 10
      spawn-interval: 400

    - category: 'AMBIENT'
      mobcap: 5
      spawn-interval: 1

    - category: 'AXOLOTLS'
      mobcap: 3
      spawn-interval: 1

    - category: 'UNDERGROUND_WATER_CREATURE'
      mobcap: 5
      spawn-interval: 1

    - category: 'WATER_CREATURE'
      mobcap: 5
      spawn-interval: 1

    - category: 'WATER_AMBIENT'
      mobcap: 5
      spawn-interval: 1

activation-range:
  enabled: true
  use-vertical-range: true
  skip-non-immune: true
  excluded-entity-types:
    - 'minecraft:minecart'
    - 'minecraft:chest_minecart'
    - 'minecraft:furnace_minecart'
    - 'minecraft:hopper_minecart'
    - 'minecraft:tnt_minecart'
  
  default-activation-type:
    activation-range: 64
    wakeup-interval: 20
    extra-height-up: true
    extra-height-down: true